### ISSUE TITLE
german layout for logitech g910 orion spectrum

### ISSUE THREAD

**Issue by giov4** [MohamadSaada/LogiGSK#14] opened 2018-01-07 12:02 UTC
hello,

as from the title, I'd like to use your software, it works, even if the volume wheel, using the US layout, was deactivated. My keyboard version is german QWERTZ.
Could it be possible to add it to your software?

Thank you

**Comment by MohamadSaada** [comment] 2018-01-25 09:51
@giov4 Hi, yes I will add the German layout very soon. but I was wondering, what do you mean by "even if the volume wheel, using the US layout, was deactivated."?

**Comment by sheppert** [comment] 2018-06-08 08:54
@MohamadSaada how is it going?

**Comment by crazydisi** [comment] 2018-06-17 11:26
Duplicate of https://github.com/MohamadSaada/LogiGSK/issues/6

**Comment by MohamadSaada** [comment] 2018-10-05 09:20
Duplicate of #6

**Closed as completed by MohamadSaada** 2018-10-05 09:20 UTC
